### ISSUE TITLE
求提供自定义ql地址接口

### ISSUE THREAD

**Issue by HowieHye** [YYWO/qrabbit#1]
<img width="815" alt="image" src="https://user-images.githubusercontent.com/36627364/217456628-56d27951-09a6-411d-b8ee-2ece49660afc.png">

**Comment by YYWO** [comment]
我只是搬运自己打包docker，作者在github: https://github.com/HT944/QRabbit  频道https://t.me/Rabbit_one 不过自定义ql地址是有的

**Comment by HowieHye** [comment]
谢谢

**Comment by NanakoOfficial** [comment]
兄弟你这个咋解决的，我也遇到了这个问题

**Comment by HowieHye** [comment]
没解决 需要去兔子那买
